# Generated by Django 5.0.2 on 2024-02-23 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clients',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('limits', models.IntegerField()),
                ('initial_balance', models.IntegerField()),
                ('actual_balance', models.IntegerField()),
            ],
            options={
                'db_table': 'clients',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Transactions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.IntegerField()),
                ('transaction_type', models.CharField()),
                ('description', models.CharField(max_length=10)),
                ('completed_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'transactions',
                'managed': False,
            },
        ),
    ]
